### PR TITLE
Unit name change

### PR DESCRIPTION
**Pull request by andremaldonado**
Just changing the name of the unit from "VivaReal" to "ZapVivaReal".

### CODE REVIEW

**Comment by priscilacng** [comment]
shouldn't we wait until the end of the week? we'll have a new name D:

**Comment by guicheffer** [comment]
yep @priscilacng, we should wait!

**Comment by igorfv** [comment]
Anyway... I think we need a new frontend test

**Comment by mezzatto** [comment]
The name is probably going to be neither any of this... Lucas will "release" the new name in the next few days...

**Comment by andremaldonado** [comment]
I will undo this change and wait until Lucas release the new name. 

Some people will see the test with the old name, no problem with this.

**Pull request closed without merging**
